### ISSUE TITLE
invalid syntax error

### ISSUE THREAD

**Issue by jennrandles** [wastatelibrary/cdm-catcher#1]
Thanks for this script! I'm running into a syntax error.  I'm trying to use json data to update page-level transcriptions for items. I'm running Python 3 on a Mac. I am getting this no matter what action I attempt. The error is under the second asterisk.
> File "cdmcatcher.py", line 116
>     params = {**self.config}
>                         ^
> SyntaxError: invalid syntax

**Comment by ghost** [comment]
I would be more than happy to look into this. What is the command that you are using in the CLI?

**Comment by jennrandles** [comment]
thank you!
`python cdmcatcher.py edit p15138coll17 websandboxtest.json`

**Comment by ghost** [comment]
I'm having trouble replicating this. Can you verify your config file and json structure? If comfortable sharing, can you email the json to me at jeremy.stroud@sos.wa.gov?

**Comment by ghost** [comment]
Closing. Issue was related to python version and missing dependecies.
